# schema version
version: "3.9"

# list of services
services:
  yo-shop:
      build:
        context: ../../
        dockerfile: ./docker/dockerfile
        target: development

      env_file: ../../env/development/app.env

      ports:
        - ${APP_PORT:-3000}:${APP_PORT:-3000} # server
        - 9229:9229 # node debugging

      depends_on:
        db:
          condition: service_healthy

      volumes:
        - ../../src:/usr/src/app/src
        - ../../dist:/usr/src/app/dist
        
  # database server
  db:
    image: postgres:14.4
    restart: always
    env_file: ../../env/development/postgres.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d yo-shop -U admin" ] # variables from the .env file cannot be referenced with $ =(
      interval: 10s
      timeout: 5s
      retries: 5

  # pgadmin
  pgadmin:
    image: dpage/pgadmin4
    env_file: ../../env/development/pgadmin.env
    volumes:
      - ../../pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
volumes:
  app:
    name: "my-app-data"
  db-data: