# версия схемы
version: "3.9"

# список служб
services:
  # сервер базы данных
  yo-shop-postgres:
    container_name: postgres_container
    image: postgres:14.4
    env_file: ../../env/development/postgres.env  # Передаём development переменные среды
    ports:
      - "5432:5432"             # пробрасываем порт что бы локальный сервер имел доступ в БД

  # администрирование бд
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file: ../../env/development/pgadmin.env # Передаём development переменные среды
    volumes:
      - ../../pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"               # пробрасываем порт для доступа через браузер
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G