# list of services
services:
  backend:
      build:
        target: development

      env_file: ../../env/development/app.env

      ports:
        - 9229:9229 # node debugging

      volumes:
        - ../../src:/usr/src/app/src
        - ../../dist:/usr/src/app/dist
        
  # database server
  db:
    env_file: ../../env/development/postgres.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}