# Образ клиента для тестирования сервера
FROM node:12-alpine
# Создаём директорию для сервера
WORKDIR /server
# Необходимые пакеты
COPY package.json .
COPY ./dist ./dist/
# Устанавливаем пакеты
RUN npm i
# Запускаем сервер
CMD ["node", "./dist/index.js"]